# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
issues:
  exclude:
    - "G304: Potential file inclusion via variable"
    - "G107: Potential HTTP request made with variable url"
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
linters:
  enable:
    - gosec
    - unconvert
    - gocyclo
    - goconst
    - goimports
    - gocritic
    - gofumpt
    - revive
linters-settings:
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G301 # Expect directory permissions to be 0750 or less
      - G302 # Expect file permissions to be 0600 or less
      - G306 # Expect WriteFile permissions to be 0600 or less
  gocritic:
    enabled-tags:
      - style
      - diagnostic
      - performance
      - opinionated
      - experimental
      - security
    disabled-checks:
      - rangeValCopy
      - ptrToRefParam
      - hugeParam
  govet:
    enable-all: true
    disable:
      - fieldalignment
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
    check-type-assertions: true
  revive:
    rules:
      # default rules:
      - name: var-declaration
      - name: dot-imports
      - name: blank-imports
      - name: indent-error-flow
      - name: range
      - name: errorf
      - name: error-naming
      - name: receiver-naming
      - name: increment-decrement
      - name: error-return
      - name: unexported-return
      - name: time-naming
      - name: context-keys-type
      - name: context-as-argument
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

      # extra rules:
      - name: atomic
      - name: bare-return
      - name: bool-literal-in-expr
      - name: comment-spacings
      - name: constant-logical-expr
      - name: datarace
      - name: deep-exit
      - name: defer
      - name: early-return
      - name: import-shadowing
