before:
  hooks:
    - script/lint
builds:
  - id: bindown
    main: ./cmd/bindown
    goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0
archives:
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
