before:
  hooks:
    - script/lint
builds:
  - id: bindown
    main: ./cmd/bindown
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    env:
      - CGO_ENABLED=0
archives:
  - id: tar.gz
    builds:
      - bindown
    format: tar.gz
  - id: binary
    builds:
      - bindown
    format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
