name: ci
on: [push]
jobs:
  cibuild:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - run: script/generate --check
        if: ${{ matrix.platform }} == ubuntu-latest
      - run: script/test
      - run: make bin/bindown
        if: ${{ matrix.platform }} == ubuntu-latest
      - run: script/lint
        if: ${{ matrix.platform }} == ubuntu-latest
