name: ci
on: [push]
jobs:
  cibuild:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version: '1.17.x'
      - run: script/generate --check
        if: "contains(matrix.platform, 'ubuntu')"
      - run: script/test
      - run: make bin/bindown
        if: "contains(matrix.platform, 'ubuntu')"
      - run: script/lint
        if: "contains(matrix.platform, 'ubuntu')"
