name: ci
on: [push]
jobs:
  cibuild:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - run: script/test
      - run: make bin/bindown
      - run: script/lint
